project_id = "euglobmdsrurbbmfargp"

[functions.mina-chat]
verify_jwt = false

[functions.calendly-integration]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.instagram-profile-check]
verify_jwt = false
